### ISSUE TITLE
Invalid type , BAD_REQUEST

### ISSUE THREAD

**Issue by Norbert-D** [nextcloud/integration_zulip#6]
Hi love to see this app great job as needed.
Not sure what I did wrong I can select a Stream and Topic so connection is valid 

When I try to send a file no matter if as upload, public or internal link I get this error but nothing in the log

Failed to send links to Zulip "Client error: `POST https:\/\/our-zulipaddress.com\/api\/v1\/messages` resulted in a `400 Bad Request` response:\n{\"result\":\"error\",\"msg\":\"Invalid type\",\"code\":\"BAD_REQUEST\"}\n\n"

I replaced our server in the error with our-zulipaddress.com

**Comment by edward-ly** [comment]
Thanks for the report, although I cannot reproduce the issue without any specific steps. For instance:

- Where exactly are you seeing that error?
- By "log", are you referring to the Nextcloud logs, the JavaScript console, or something else?
- What kind of file are you trying to send?

Any screenshots you can provide would be helpful too.

**Comment by edward-ly** [comment]
Closing due to no response. Please update the app to the latest version if you haven't already to see if that has fixed your problem. If not, feel free to reopen this issue with additional information.
